services:
  valheim:
    image: mbround18/valheim:latest
    user: steam
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "2456:2456/udp"
      - "2457:2457/udp"
      - "2458:2458/udp"
    volumes:
    - ./tmp/valheim:/home/steam/valheim
