services:
  valheim:
    image: mbround18/valheim:latest
    user: steam
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 2456:2456
    volumes:
    - ./tmp/valheim:/home/steam/valheim
